### PR TITLE
[conference] Add tw/mopcon & add API.cfg in gitignore

### PR DESCRIPTION
**Pull request by hashman**
Hi TGmeetup team,

I'm Hash one of mopcon organizer. I'd like to add MOPCON information in this repo.

Thank you.

### CODE REVIEW

**Comment by sufuf3** [comment]
Cool! Thanks for your contribution.
Would you please also add `conference/tw/MOPCON/README.md`?
This is for https://github.com/TGmeetup/tgmeetup.js/issues?q=is%3Aissue+is%3Aopen+label%3AEvent. We will show the conference information URL which will redirect to `conference/tw/MOPCON/README.md` path.

Many thanks.

**Comment by hashman** [comment]
@sufuf3 ok please hold :)

**Comment by hashman** [comment]
@sufuf3 done :) check if everything looks okay

**Comment by hashman** [comment]
@sufuf3 How about this 🙈

**Comment by sufuf3** [comment]
Thank you 👍

**Pull request merged**
