### PR TITLE
[community] Add HPXKH

### PR DESCRIPTION
**Pull request by eggttball**
加入 HPXKH 社群
HPXKH 即為 Happy People Cross for Kaohsiung, 是 HPX 在高雄在地的讀書會。提供高雄愛書的朋友們一個呼朋引伴的環境。任何社員都可以在這裡舉辦讀書聚會，開啟多元化主題的交流，舉凡產品、服務>、行銷、設計、人類、心理、哲學、社會、商業、管理、技術、科技、創業。後續透過輕鬆聚或大聚互相分享彼此的心得，以書會友，共同成長。

### CODE REVIEW

**Comment by sufuf3** [comment]
Thank you.
Would you please add ` community/tw/HPXKH/README.md`?
Like https://github.com/TGmeetup/TGmeetup/blob/2e98e331b2ad314e339315b3a4edf1c784a04337/community/tw/Cloud-Native-User-Group-Taiwan/README.md

We update the event information on https://github.com/TGmeetup/tgmeetup.js/issues?q=is%3Aissue+is%3Aopen+label%3AEvent by our bot.
Therefore, we want to show the community README.md link to let people know.

Many thanks

**Comment by eggttball** [comment]
@sufuf3 OK, Done !

**Comment by sufuf3** [comment]
@eggttball The HPXKH README path should be `community/tw/HPXKH/README.md`
Not the README file under root path.
Would you please revise it?
Many thanks

**Comment by eggttball** [comment]
@sufuf3 
Fixed again. I get distracted for previous commit.

**Pull request merged**
